import type {ComponentCapability} from './primitives/types';

export const CAPABILITY_REGISTRY: ComponentCapability[] = [
  // ── Existing scene components ──────────────────────────────────────────────
  {
    id: 'KineticTypoScene',
    type: 'scene',
    supportedActions: ['enter', 'reveal', 'hold', 'explode'],
    supportedObjectTypes: ['text'],
    supportedLayouts: ['centered'],
    durationRange: {min: 2, max: 6},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['text', 'fontSize', 'color'],
  },
  {
    id: 'TokenStreamScene',
    type: 'scene',
    supportedActions: ['generate', 'stamp', 'transform', 'reveal', 'hide', 'enter', 'exit', 'hold', 'connect', 'travel', 'fill'],
    supportedObjectTypes: ['token', 'stamp', 'text', 'block'],
    supportedLayouts: ['full-canvas'],
    durationRange: {min: 4, max: 12},
    artDirectionFamilies: 'all',
    multiBeat: true,
    maxBeats: 8,
    configurableProperties: ['tokens', 'phases', 'stampText', 'outputBlock'],
  },
  {
    id: 'CTAScene',
    type: 'scene',
    supportedActions: ['enter', 'reveal', 'hold'],
    supportedObjectTypes: ['text', 'icon'],
    supportedLayouts: ['centered'],
    durationRange: {min: 2, max: 5},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['channel', 'callToAction'],
  },
  {
    id: 'LayerRevealScene',
    type: 'scene',
    supportedActions: ['reveal', 'exit'],
    supportedObjectTypes: ['block', 'label'],
    supportedLayouts: ['vertical-stack'],
    durationRange: {min: 4, max: 10},
    artDirectionFamilies: 'all',
    multiBeat: true,
    maxBeats: 4,
    configurableProperties: ['layers'],
  },
  {
    id: 'CardStackScene',
    type: 'scene',
    supportedActions: ['enter', 'exit', 'reveal'],
    supportedObjectTypes: ['card'],
    supportedLayouts: ['fan'],
    durationRange: {min: 4, max: 10},
    artDirectionFamilies: 'all',
    multiBeat: true,
    maxBeats: 6,
    configurableProperties: ['cards'],
  },
  {
    id: 'MeterScene',
    type: 'scene',
    supportedActions: ['fill', 'compare'],
    supportedObjectTypes: ['gauge'],
    supportedLayouts: ['horizontal-pipeline'],
    durationRange: {min: 4, max: 10},
    artDirectionFamilies: 'all',
    multiBeat: true,
    maxBeats: 4,
    configurableProperties: ['meters', 'labels'],
  },
  {
    id: 'DataFlowScene',
    type: 'scene',
    supportedActions: ['travel', 'enter', 'connect'],
    supportedObjectTypes: ['block', 'arrow'],
    supportedLayouts: ['horizontal-pipeline'],
    durationRange: {min: 4, max: 10},
    artDirectionFamilies: 'all',
    multiBeat: true,
    maxBeats: 4,
    configurableProperties: ['nodes', 'edges'],
  },
  {
    id: 'TakeawayScene',
    type: 'scene',
    supportedActions: ['enter', 'reveal', 'hold'],
    supportedObjectTypes: ['token', 'text'],
    supportedLayouts: ['centered'],
    durationRange: {min: 3, max: 8},
    artDirectionFamilies: 'all',
    multiBeat: true,
    maxBeats: 3,
    configurableProperties: ['takeaway', 'tokens'],
  },

  // ── Reusable primitives (Scene Composer v1) ────────────────────────────────
  {
    id: 'EnterExit',
    type: 'primitive',
    supportedActions: ['enter', 'exit'],
    supportedObjectTypes: ['text', 'token', 'block', 'card', 'label', 'icon', 'stamp'],
    supportedLayouts: ['full-canvas', 'centered'],
    durationRange: {min: 0.3, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['enterStyle', 'exitStyle', 'exitBeat', 'children'],
  },
  {
    id: 'StampOverlay',
    type: 'primitive',
    supportedActions: ['stamp', 'enter', 'reveal'],
    supportedObjectTypes: ['stamp', 'text'],
    supportedLayouts: ['full-canvas'],
    durationRange: {min: 0.3, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['text', 'impact', 'target', 'color', 'angle', 'fontSize'],
  },
  {
    id: 'ColorTransform',
    type: 'primitive',
    supportedActions: ['transform'],
    supportedObjectTypes: ['token', 'ribbon', 'block', 'text'],
    supportedLayouts: ['full-canvas'],
    durationRange: {min: 0.5, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['fromColor', 'toColor', 'easing', 'children'],
  },
  {
    id: 'CameraTransform',
    type: 'primitive',
    supportedActions: ['zoom', 'track'],
    supportedObjectTypes: ['zone'],
    supportedLayouts: ['full-canvas'],
    durationRange: {min: 1, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['operation', 'intensity', 'children'],
  },
  {
    id: 'ConnectArrow',
    type: 'primitive',
    supportedActions: ['connect', 'reveal'],
    supportedObjectTypes: ['arrow'],
    supportedLayouts: ['full-canvas'],
    durationRange: {min: 0.5, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['from', 'to', 'label', 'style', 'color'],
  },
  {
    id: 'TravelPath',
    type: 'primitive',
    supportedActions: ['travel'],
    supportedObjectTypes: ['token', 'block', 'document', 'icon'],
    supportedLayouts: ['full-canvas'],
    durationRange: {min: 0.5, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['waypoints', 'trail', 'children'],
  },
  {
    id: 'SpatialZone',
    type: 'primitive',
    supportedActions: ['reveal', 'enter', 'hold'],
    supportedObjectTypes: ['zone', 'label'],
    supportedLayouts: ['full-canvas'],
    durationRange: {min: 0.5, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['bounds', 'label', 'borderStyle', 'color'],
  },
  {
    id: 'DualLaneLayout',
    type: 'primitive',
    supportedActions: ['split', 'compare'],
    supportedObjectTypes: ['lane'],
    supportedLayouts: ['dual-lane'],
    durationRange: {min: 2, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['topLane', 'bottomLane', 'dividerStyle', 'topChildren', 'bottomChildren'],
  },
  {
    id: 'GaugeArc',
    type: 'primitive',
    supportedActions: ['fill', 'drain'],
    supportedObjectTypes: ['gauge'],
    supportedLayouts: ['centered', 'full-canvas'],
    durationRange: {min: 1, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['targetValue', 'fillColor', 'zones', 'title', 'valueLabel', 'pulse'],
  },
  {
    id: 'ObjectBlock',
    type: 'primitive',
    supportedActions: ['enter', 'reveal', 'hold', 'hide'],
    supportedObjectTypes: ['block', 'label', 'icon'],
    supportedLayouts: ['full-canvas'],
    durationRange: {min: 0.3, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['label', 'position', 'blockStyle', 'icon', 'sublabel', 'color'],
  },
  {
    id: 'CardFan',
    type: 'primitive',
    supportedActions: ['enter', 'reveal', 'hold'],
    supportedObjectTypes: ['card', 'document'],
    supportedLayouts: ['fan'],
    durationRange: {min: 1, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['cards', 'origin', 'spreadAngle', 'holdAll'],
  },
  {
    id: 'RibbonObject',
    type: 'primitive',
    supportedActions: ['generate', 'travel', 'enter'],
    supportedObjectTypes: ['token', 'ribbon'],
    supportedLayouts: ['full-canvas', 'horizontal-pipeline'],
    durationRange: {min: 1, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: false,
    configurableProperties: ['tokens', 'startPos', 'endPos', 'emissionRate', 'showConnector'],
  },
  {
    id: 'ComposedScene',
    type: 'scene',
    supportedActions: ['enter', 'exit', 'travel', 'track', 'zoom', 'split', 'merge', 'transform',
      'reveal', 'hide', 'connect', 'fill', 'drain', 'generate', 'collapse', 'explode',
      'compare', 'stamp', 'hold'],
    supportedObjectTypes: ['text', 'token', 'ribbon', 'block', 'card', 'gauge', 'arrow',
      'zone', 'label', 'stamp', 'icon', 'document', 'lane'],
    supportedLayouts: ['full-canvas', 'centered', 'horizontal-pipeline', 'vertical-stack',
      'dual-lane', 'radial', 'scatter', 'fan', 'grid'],
    durationRange: {min: 1, max: 60},
    artDirectionFamilies: 'all',
    multiBeat: true,
    maxBeats: 12,
    configurableProperties: ['layers', 'camera'],
  },
];

export function getCapability(id: string): ComponentCapability | undefined {
  return CAPABILITY_REGISTRY.find(c => c.id === id);
}

export function supportsAction(id: string, action: string): boolean {
  const cap = getCapability(id);
  return cap ? cap.supportedActions.includes(action as never) : false;
}

export function getAllPrimitives(): ComponentCapability[] {
  return CAPABILITY_REGISTRY.filter(c => c.type === 'primitive');
}

export function getAllScenes(): ComponentCapability[] {
  return CAPABILITY_REGISTRY.filter(c => c.type === 'scene');
}
